id: AEE4B877D
title: Summoning the Spirit of Abundance - The Hook of Divine Substance
type: translation
pechas:
- I8427855E
- I18912A74
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:04:49.552885
  last_modified_at: 2023-01-04 13:04:49.552892
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I8427855E/5FA4: B855
  I18912A74/9753: B855
